### PR TITLE
add uninstall script

### PR DESCRIPTION
**Pull request by matthiasdiener**

### CODE REVIEW

**Comment by inducer** [comment]
Not sure I get the need. `rm -Rf emirge` or rm -rf "$conda_prefix" do the trick, no?

**Comment by matthiasdiener** [comment]
> Not sure I get the need. `rm -Rf emirge` or rm -rf "$conda_prefix" do the trick, no?

Right, `rm -rf "$conda_prefix" ` would do most of it. However,

- this might not be clear to users
- it doesn't remove the shell activation code
- users might not be even aware where conda / the others were installed.

**Comment by inducer** [comment]
> it doesn't remove the shell activation code

Do we still silently put stuff into people's `.bashrc`? If so, we should stop *right away*.

**Comment by matthiasdiener** [comment]
> > it doesn't remove the shell activation code
> 
> Do we still silently put stuff into people's `.bashrc`? If so, we should stop _right away_.

We do run `conda init` in `install.sh`.

**Comment by inducer** [comment]
> users might not be even aware where conda / the other packages were installed.

We're spending time teaching them to activate the environment. That should tell them where stuff lives IMO.

**Comment by inducer** [comment]
> Independent of whether we put stuff into .bashrc or not, we should probably run conda init --reverse when uninstalling.

I disagree. IMO: Sane software does not randomly change stuff outside of its installation folder unless explicitly requested, even to correct past mistakes in that regard.

**Comment by matthiasdiener** [comment]
> > Independent of whether we put stuff into .bashrc or not, we should probably run conda init --reverse when uninstalling.
> 
> IMO: Sane software does not randomly change stuff outside of its installation folder unless explicitly requested, even to correct past mistakes in that regard.





> > Independent of whether we put stuff into .bashrc or not, we should probably run conda init --reverse when uninstalling.
> 
> I disagree. IMO: Sane software does not randomly change stuff outside of its installation folder unless explicitly requested, even to correct past mistakes in that regard.

It's not about correcting past mistakes, but the user might have run `conda init` himself, and when removing conda that added code would be useless.

**Pull request closed without merging**
